export const data = [
  {
    id: 1,
    name: 'Leanne Graham',
    username: 'Bret',
    email: 'Sincere@april.biz',
    message: 'How are you doing 1',
    date: 'Fri Jul 15 2022 10:10:59 GMT+0530 ',
    unreadMessages: 1,
    url: 'https://picsum.photos/id/1/200',
  },
  {
    id: 2,
    name: 'Ervin Howell',
    username: 'Antonette',
    email: 'Shanna@melissa.tv',
    message: 'How are you doing 2',
    date: 'Fri Jul 15 2022 10:12:59 GMT+0530 ',
    unreadMessages: 2,
    url: 'https://picsum.photos/id/2/200',
  },
  {
    id: 3,
    name: 'Clementine Bauch',
    username: 'Samantha',
    email: 'Nathan@yesenia.net',
    message: 'How are you doing 3',
    date: 'Fri Jul 15 2022 10:13:59 GMT+0530 ',
    unreadMessages: 0,
    url: 'https://picsum.photos/id/3/200',
  },
  {
    id: 4,
    name: 'Patricia Lebsack',
    username: 'Karianne',
    email: 'Julianne.OConner@kory.org',
    message: 'How are you doing 4',
    date: 'Fri Jul 15 2022 10:14:59 GMT+0530 ',
    unreadMessages: 0,
    url: 'https://picsum.photos/id/4/200',
  },
  {
    id: 5,
    name: 'Chelsey Dietrich',
    username: 'Kamren',
    email: 'Lucio_Hettinger@annie.ca',
    message: 'How are you doing 5',
    date: 'Fri Jul 15 2022 10:15:59 GMT+0530 ',
    unreadMessages: 0,
    url: 'https://picsum.photos/id/5/200',
  },
  {
    id: 6,
    name: 'Mrs. Dennis Schulist',
    username: 'Leopoldo_Corkery',
    email: 'Karley_Dach@jasper.info',
    message: 'How are you doing 6',
    date: 'Fri Jul 15 2022 10:16:59 GMT+0530 ',
    unreadMessages: 1,
    url: 'https://picsum.photos/id/6/200',
  },
  {
    id: 7,
    name: 'Kurtis Weissnat',
    username: 'Elwyn.Skiles',
    email: 'Telly.Hoeger@billy.biz',
    message: 'How are you doing 7',
    date: 'Fri Jul 15 2022 10:17:59 GMT+0530 ',
    unreadMessages: 3,
    url: 'https://picsum.photos/id/7/200',
  },
  {
    id: 8,
    name: 'Nicholas Runolfsdottir V',
    username: 'Maxime_Nienow',
    email: 'Sherwood@rosamond.me',
    message: 'How are you doing 8',
    date: 'Fri Jul 15 2022 10:18:59 GMT+0530 ',
    unreadMessages: 3,
    url: 'https://picsum.photos/id/8/200',
  },
  {
    id: 9,
    name: 'Glenna Reichert',
    username: 'Delphine',
    email: 'Chaim_McDermott@dana.io',
    message: 'How are you doing 9',
    date: 'Fri Jul 15 2022 10:19:59 GMT+0530 ',
    unreadMessages: 1,
    url: 'https://picsum.photos/id/9/200',
  },
  {
    id: 10,
    name: 'Clementina DuBuque',
    username: 'Moriah.Stanton',
    email: 'Rey.Padberg@karina.biz',
    message: 'How are you doing 10',
    date: 'Fri Jul 15 2022 10:20:59 GMT+0530 ',
    unreadMessages: 1,
    url: 'https://picsum.photos/id/10/200/200',
  },
];
